[package]
name = "repo"
version = "0.1.0"
authors = ["Sam Lakerveld <darkwater124@gmail.com>"]
edition = "2018"

[dependencies]
rocket         = "0.4.0"
rocket_contrib = "0.4.0"
serde          = "1.0.84"
serde_derive   = "1.0.84"
serde_json     = "1.0.34"
